// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaocr3tSsxd9e4ZHg3zZI3IOm8cThAPnQ',
    appId: '1:776268691579:web:c5abcae2930f801a9d8ade',
    messagingSenderId: '776268691579',
    projectId: 'carepaw-93d16',
    authDomain: 'carepaw-93d16.firebaseapp.com',
    storageBucket: 'carepaw-93d16.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGHVfBgm_ja4JsPEiicZRDV26qZN4Z_dM',
    appId: '1:776268691579:android:4292c4c7d27405ab9d8ade',
    messagingSenderId: '776268691579',
    projectId: 'carepaw-93d16',
    storageBucket: 'carepaw-93d16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqQh-t6p9HD6QbmPsUNnK-mc4LZ6IK5fg',
    appId: '1:776268691579:ios:298fd60af8fc17279d8ade',
    messagingSenderId: '776268691579',
    projectId: 'carepaw-93d16',
    storageBucket: 'carepaw-93d16.firebasestorage.app',
    iosBundleId: 'com.example.carepaw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqQh-t6p9HD6QbmPsUNnK-mc4LZ6IK5fg',
    appId: '1:776268691579:ios:298fd60af8fc17279d8ade',
    messagingSenderId: '776268691579',
    projectId: 'carepaw-93d16',
    storageBucket: 'carepaw-93d16.firebasestorage.app',
    iosBundleId: 'com.example.carepaw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaocr3tSsxd9e4ZHg3zZI3IOm8cThAPnQ',
    appId: '1:776268691579:web:6f018168d4b13f879d8ade',
    messagingSenderId: '776268691579',
    projectId: 'carepaw-93d16',
    authDomain: 'carepaw-93d16.firebaseapp.com',
    storageBucket: 'carepaw-93d16.firebasestorage.app',
  );
}
